apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: "nats"
  namespace: "nats"
spec:
  network:
    expose: []
    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: IntraNamespace
      - direction: Egress
        remoteGenerated: Anywhere
