tasks:
  - name: health-check
    actions:
      - description: Package Deployment Health Check
        wait:
          cluster:
            kind: Deployment
            name: uds-package-app
            namespace: uds-package-app-ns
            condition: Available

      # StatefulSets don't show conditions themselves so we look for an underlying Pod
      - description: Gitlab Gitaly Health Check
        wait:
          cluster:
            kind: Pod
            name: app=uds-package-app
            namespace: uds-package-app-ns
            condition: Ready

  - name: ingress
    actions:
      - description: Package UI Health Check
        wait:
          network:
            protocol: https
            address: hostname-for-uds-package.uds.dev
            code: 200
