apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: gitness
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: Gitness SSO
      clientId: uds-core-gitness
      redirectUris:
        - "https://gitlab.{{ .Values.domain }}/users/auth/openid_connect/callback"
  {{- end }}
  network:
    expose:
      - service: gitness
        podLabels:
          app.kubernetes.io/name: gitness
        host: gitness
        gateway: tenant
        port: 3000
    allow:

      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Egress
        selector:
          app.kubernetes.io/name: gitness
        {{- if .Values.postgres.internal }}
        remoteNamespace: {{ .Values.postgres.namespace | quote }}
        remoteSelector:
          {{ .Values.postgres.selector | toYaml | nindent 10 }}
        port: {{ .Values.postgres.port }}
        {{- else }}
        remoteGenerated: Anywhere
        {{- end }}
        description: "Gitness Postgres"


      - direction: Egress
        remoteGenerated: IntraNamespace

      - direction: Egress
        # todo: this is over permissive, need to scope it down
        remoteGenerated: KubeAPI


      - direction: Egress
        podLabels:
          app: gitness
        port: 443
        description: "SSO"
