variables:
  postgres-operator:
    postgresql:
      enabled: true  # Set to false to not create the PostgreSQL resource
      teamId: "uds"
      volume:
        size: "10Gi"
      numberOfInstances: 2
      users:
        gitness.gitness: []
      databases:
        gitness: gitness.gitness
      version: "13"
      ingress:
        remoteGenerated: Anywhere

